package nettyServer;

import java.util.Date;

/**
 * Simple helping class to store information about ip. It stores the number of
 * requests (received from this ip) and the time of last request.
 * <b>Autogenerated methods hashCode() and equals() use only ip field!</b>.
 * 
 * @author rk
 * 
 */
public class IpInfo {
	
	private String ip;
	private int requestsCount;
	private Date timeOfLastRequest;
	
	public IpInfo(String ip) {
		this.ip = ip;
		requestsCount = 1;
		timeOfLastRequest = new Date();
	}

	/**
	 * This method updates the number of requests made from this ip
	 * and set up a new date. Call this method after you 
	 * sure that {@link ServerStatistics} contains this IpInfo class.
	 * 
	 * @see {@link ServerStatistics}
	 */
	public void update() {
		++requestsCount;
		timeOfLastRequest = new Date();
	}
	
	public String getIp() {
		return ip;
	}

	public int getRequestsCount() {
		return requestsCount;
	}

	public Date getTimeOfLastRequest() {
		return timeOfLastRequest;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ip == null) ? 0 : ip.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		IpInfo other = (IpInfo) obj;
		if (ip == null) {
			if (other.ip != null)
				return false;
		} else if (!ip.equals(other.ip))
			return false;
		return true;
	}
}
