package nettyServer;

import java.util.Date;

/**
 * Simple helping class to store information about ip. It stores the amount of
 * requests (received from this ip) and the time of last request.
 * <b>Methods hashCode() and toString() autogenerated using only ip field!</b>.
 * 
 * @author rk
 * 
 */
public class IpInfo {
	
	private String ip;
	private int requestsCount;
	private Date dateOfLastRequest;
	
	public IpInfo(String ip) {
		this.ip = ip;
		requestsCount = 1;
		dateOfLastRequest = new Date();
	}

	public void update() {
		++requestsCount;
		dateOfLastRequest = new Date();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((ip == null) ? 0 : ip.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		IpInfo other = (IpInfo) obj;
		if (ip == null) {
			if (other.ip != null)
				return false;
		} else if (!ip.equals(other.ip))
			return false;
		return true;
	}
}
